
#+begin_src yaml :exports results :results value html
  ---
  title: Teaching abstract frameworks in general education
  date: 2023-10-08
  math: true
  mermaid: true
  categories: [education]
  tags: [complex-adaptive systems, generative processes, statistics, cognitive biases, education]
  ---

#+end_src

It's a mighty long time ago that I left school.
Since then, my "scientific career" has essentially been a weak excuse to keep doing what I enjoy the most: explore different corners of the scientific landscape in an effort to make sense, to reduce surprise by what-the-flying-kaka is happening out there and in here.

There are a number of things that I wish someone had taught me much earlier.
It is difficult to judge how realistic that wish is; how much it would even have been possible to understand some of things earlier.
But let us be daring and speculate that there are things that everybody in, say, late school education might benefit from internalizing, even though these things are not taught at all.
In my mind, these are not more facts or concrete skills, but entirely abstract ideas, ways of thinking about the world.
Here, the case is made for two such abstract principles: thinking explicitly in terms of *generative-process models* and *complex-adaptive systems*.

There are many other things that would likely be of benefit to include more into high-school education.
Probability theory comes to mind, maybe together with a descriptive (not normative or idealized) picture of how empirical research is clustered around a shaky bottleneck of measurement, statistics and interpretation of statistical results.
Learning about cognitive biases early on might also pay off.
But the main big picture ideas that I would defend are useful /tout court/ are foundational to a very general sense-making approach to the natural world.

* Generative-process models

TBC


* Complex-adaptive systems
